.github/workflows/deploy.yml
.github/workflows/diff.yml
lib/secret.ts
main.ts
package.json
provider.json
yarn.lock

- https://github.com/hashicorp/cdktf-provider-azurerm/issues/446
- https://github.com/hashicorp/terraform-cdk/issues/1019

Add azuread Provider

---

provider.json

See upgrade guide for breaking changes: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/version-4-upgrade

chore!: update AWS provider to v4

---

provider.json

In relation to https://github.com/hashicorp/terraform-cdk/issues/1712 this adds the DigitalOcean Terraform provider.

feat: add digitalocean TF provider

---

projenrc.template.js

This is in preparation for changes to cdktf-provider-project that include the provider version in the package (0.10.3 exposes that information)

chore: require cdktf 0.10.3

---

provider.json

Although this is destructive we will do it since the published packages stay

fix: rename repo for dnsimple provider

---

projenrc.template.js

Due to an accidentally introduced incompatibility in cdktf 0.12.2, the latest pre-built providers now require at least cdktf 0.12.2

fix!: Due to an accidentally introduced incompatibility in cdktf 0.12.2, the latest pre-built providers now require at least cdktf 0.12.2

---

.github/workflows/upgrade-repositories.yml
projenrc.template.js
providersWithCustomRunners.json

DO NOT MERGE
... until https://github.com/hashicorp/cdktf-provider-project/pull/247 has been merged and released. Because this PR adds an currently unknown option to the Projen project and we first need to update the Projen project version itself (using the very same command that we change in this PR)
Else we'd need to manually update the Projen project version in all 38 provider repositories 😅

feat: set useCustomGithubRunner option for some providers

---

provider.json

Related to: https://github.com/hashicorp/terraform-cdk/issues/2135
This PR imports the [hashicups](https://github.com/hashicorp/terraform-provider-hashicups) provider. We will use this provider to test the migration steps of prebuilt-providers, to prevent any accidental outages.

Add hashicups as a prebuilt provider for testing provider migration

---

projenrc.template.js

Note: The breaking change detection when rolling out this change will still work (and *not* detect a breaking change for this change), as it parses only the first valid version which in this case will end up being `0.12.2`. Refer to the used regex here: https://github.com/hashicorp/cdktf-repository-manager/blob/955b2c051e981266fc4ae4118424f0d694714147/.github/workflows/upgrade-repositories.yml#L91
The provider add command supports these advanced version ranges as well because it uses the semver package to check if the used cdktf version satisfies the range from the published package: https://github.com/hashicorp/terraform-cdk/blob/550d0cc927df1a62d69acdb184576ec3a583e5f8/packages/cdktf-cli/lib/dependencies/prebuilt-providers.ts#L204

feat: enable ^0.12.2 bindings to work with the next cdktf version (^0.13.0)

---

.github/workflows/upgrade-repositories.yml

Since we've moved all the pre-built providers to the `cdktf` Github organization, and the new official pre-built providers were never a part of the `hashicorp` Github org, this PR will update the `upgrade-repositories` github action workflow to reference the current repository URL.

fix: use correct org name for prebuilt providers in action

---

.github/lib/comment-plan-output.js
.github/lib/create-pr.js
.github/lib/create-projen-files.js
.github/lib/detect-breaking-changes.js
.github/workflows/diff.yml
.github/workflows/upgrade-repositories.yml
.gitignore

⬆️ I would like to move all the JS scripts we use within this repo to their own files. The benefits are that we get syntax highlighting for the scripts, and the github action workflow files become more concise. 
⬇️ The problem with the refactor though is that I don't have a good way of testing this. So, this might cause some breakages and I'll be observing the workflows after merge and make fix PRs as we see problems.

chore: Extract javascript script from workflows into their own files

---

main.ts

This is the reason why so many PR checks are blocked. Apparently when a check has a 'name' field, then Github only checks that instead of the job's key in the workflow yaml.

chore: when check has name field, use name

---

.github/workflows/lock.yml
.github/workflows/stale.yml

Since I've added these to every other repo we manage, I figured I'd hit this one up as well. 😄

chore: add workflows for closing and locking old issues and PRs

---

.github/workflows/gh-action-upgrade.yml

This is mostly a direct copy of the file used in hashicorp/terraform-cdk#2422 - I was trying to figure out how to enforce this security policy in all of our repos. The Projen-based repos are going to be tougher but since this repo isn't using Projen, I figured adding this file here is easy.

chore: add workflow to upgrade github actions

---

.github/workflows/gh-action-upgrade.yml

Copying over the fix from hashicorp/terraform-cdk#2546 now that I finally got it working because otherwise this workflow gets annoying real fast.

chore: autoclose older GHA updater PRs

---

projenrc.template.js

as the next version of @cdktf/provider-project will stop specifying the devDep itself and start using those that were passed to it
Related to https://github.com/cdktf/cdktf-provider-project/pull/264
This has no effect until that other PR is merged and released, as the current provider project just overrides all devDependencies.

feat: explicitly specify devDependency on @cdktf/provider-project

---

lib/repository.ts

This PR adds a codeowners file to all prebuilt provider go repositories that are populated by each provider's release process. 
Since the `-go` repositories are somewhat special, I'm going to try this method out as it seems the most straightforward. Since the repositories aren't projen repositories, but only hold the output of the go release, they are somewhat hard to impact directly from modifying cdktf-provider-project.
One thing I'm not sure about is whether the release process will overwrite the `.github/CODEOWNERS` file.

chore: Add codeowners to all cdktf-provider-{name}-go repositories

---

.copywrite.hcl
.github/ISSUE_TEMPLATE/request-provider.yml
.github/lib/.eslintrc.js
.github/lib/collect-changes.js
.github/lib/comment-plan-output.js
.github/lib/create-pr.js
.github/lib/create-projen-files.js
.github/workflows/add-copyright-headers.yml
.mergify.yml
lib/index.ts
lib/repository.ts
lib/secrets.ts
main.ts
projenrc.template.js

This creates a new commit on each PR à la Projen self-mutation, which has the benefit that you don't have to have the Copywrite tool installed on your own system (nicer for OSS contributors).

chore: add copyright headers automation

---

.github/lib/copy-codeowners-file.js
.github/lib/create-pr.js
.github/workflows/add-codeowners.yml
assets/codeowners
lib/repository.ts

There's an issue with the github provider where it fails to validate the `main` branch somehow. The error message isn't very clear, but it seems to either be an issue with the github token (which I've validated manually, does work, so that's unlikely), or the code within the Github provider.
Thus, I'm reverting that change, and going the route of a manual github action workflow that will add CODEOWNERS files to each -go repo. This is a less than ideal approach, but at this point I don't have a better idea and it's not worth spending any more time on this.

Fix: Failing config used to generate CODEOWNERS file in `cdktf-provider-{providerName}-go` repos

---

.github/workflows/add-codeowners.yml

git diff doesn't tell us about untracked files, so using a hacky git status workaround

fix: CODEOWNERS workflow should make a PR for a newly added file

---

.github/workflows/add-copyright-headers.yml

Use `pull_request_target` so that this can run successfully for outside contributors as well.

chore: fix copyright headers automation

---

lib/repository.ts

Every now and then we get stray issues reported to the `-go` repos which tend to disappear into the ether because we don't monitor these. The easiest thing to do is just turn off the Issues tab in these repos since we don't use it ourselves anyway.

fix: turn off Issues tab for go repos

---

.github/workflows/add-license.yml

I tried running this script for the first time this morning and it failed. Looking into how this works in the Copywrite tool led me to https://github.com/cli/go-gh#go-library-for-the-github-cli which got me hoping that maybe all this is missing is this `GH_REPO` env var. Might be a long shot, though.

fix: set GH_REPO env var in Go license script

---

.github/workflows/add-copyright-headers.yml

Minor nitpick but we don't need to pass the token anymore with the newer version.

chore: remove unused input from copywrite

---

provider.json
sharded-stacks.json

Setting up the PR as requested by Chris -- however, let's wait to merge this until we have a chance to discuss:
When I set up #208 to create the Waypoint provider recently, it mostly went fine (once the Maven issues were resolved), but the provider got created as v0.0.0 instead of v1.0.0: https://github.com/cdktf/cdktf-provider-waypoint/releases I thought we had some code in place to force the first version to be v1, but if we do, that functionality doesn't seem to be working.

feat: add LaunchDarkly provider

---

.github/lib/collect-changes.js

This is relatively minor, but it's been bothering me for a while that our individual providers often end up with changelogs like:
> • deps: Updated ([#549](https://github.com/cdktf/cdktf-provider-snowflake/issues/549)) ([df79e2e](https://github.com/cdktf/cdktf-provider-snowflake/commit/df79e2e7d7410ac9d0e9849061a61fe326601029))
• deps: Updated ([#556](https://github.com/cdktf/cdktf-provider-snowflake/issues/556)) ([ab6c52d](https://github.com/cdktf/cdktf-provider-snowflake/commit/ab6c52d7767b3c7ec57ce4c2676bcd5d2e5755fc))
• deps: Updated ([#558](https://github.com/cdktf/cdktf-provider-snowflake/issues/558)) ([28913f7](https://github.com/cdktf/cdktf-provider-snowflake/commit/28913f7b036f9602e5f0da713eb5ff11196aff11))
• deps: Updated …

fix: show triggering commit in provider PR titles

---

scripts/force-release-providers.sh

Recently we had a situation where we released a new version of CDKTF, and then promptly triggered all prebuilt providers to be re-generated. However, the go release failed on every prebuilt provider. Our current CI implementation on the providers doesn't allow us to manually release a version for just a specific language, so I built the [force-release workflow](https://github.com/cdktf/cdktf-provider-project/blob/main/src/force-release.ts) that's present on every provider. Even then, running that workflow manually by finding the right SHA for the PR and then triggering the release is too cumbersome at this scale. Thus, this script was created and it can be used to (_very carefully, please_) run the force-release workflow across the entire prebuild provider portfolio

chore: Add script for running `force-release` on every provider

---

provider.json

v2.0 of the Nomad provider went generally available last week. This updates it on our side.

chore: update Nomad to v2

---

.github/workflows/deploy-cdktf-stacks.yml
.github/workflows/diff-cdktf-stacks.yml
cdktf.json
lib/logical-id-override.ts
lib/repository.ts
lib/secrets.ts
lib/unique-id-override.ts
main.ts
package.json
tsconfig.json
yarn.lock

Please review the diffs
Closes hashicorp/terraform-cdk#2549

chore: upgrade to cdktf 0.17 and tsx

---

package.json
yarn.lock

Needed to use an older version so that we can use `require()` rather than ESM.

chore: fix usage of node-fetch in upgrade workflow

---

provider.json

v3 of the PD provider is out so we should upgrade our version: https://github.com/PagerDuty/terraform-provider-pagerduty/releases

chore: update PagerDuty to v3

---

.github/workflows/upgrade-cdktf.yml

This workflow adapts scripts we're using elsewhere already like https://github.com/hashicorp/cdktf-aws-cdk/blob/main/.github/workflows/upgrade-cdktf.yml and https://github.com/hashicorp/terraform-cdk-action/blob/main/.github/workflows/upgrade-cdktf.yml to automatically create a PR to upgrade CDKTF when new (non-patch) versions come out. This variant creates two PRs:
- one to upgrade CDKTF on the prebuilt provider repos; for now, I've left the automerge label off so it will depend on us to manually approve the PR before it is merged (if anyone disagrees with that, let me know, but I feel like that's generally how we've done things)
- a draft PR to upgrade CDKTF on this repo, which will depend on the above PR being merged first (because the GitHub provider will need to be updated before …

feat: automate upgrading CDKTF

---

.github/workflows/upgrade-repositories.yml

We continue to run into Github errors with our user creating PRs and setting labels. Hopefully this change improves that situation and fails less.
Ideally, the Github CLI would honor rate limits and retry automatically, but it doesn't support that at this time: https://github.com/cli/cli/issues/3292
Fixes # 

fix: decrease max-parallel from 10 to 5 for provider upgrades

---

provider.json
sharded-stacks.json

This reverts #211 -- the provider was never deployed successfully and requires aws/jsii#4299 to be fixed in order to work. Removing it from our workflows is the best thing to do in the meantime.

fix: remove oci provider

---

projenrc.template.js

While our systems will treat this as a major breaking change, I think it should be relatively safe to merge because most of these versions are what is already in use in practice.
- `constructs`: [example](https://github.com/cdktf/cdktf-provider-aws/blob/main/yarn.lock#L1242-L1243) showing `10.3.0` is already what is being used
- `jsii`: [example](https://github.com/cdktf/cdktf-provider-aws/blob/main/yarn.lock#L2660-L2661) showing `5.2.33` is already what is being used
The only one that's new/different is the TypeScript version, but that's actually what prompted this change. Not only are the individual prebuilt provider repos [still using `^3.9.10`](https://github.com/cdktf/cdktf-provider-aws/blob/main/yarn.lock#L4144-L4145) (i.e. a _very_ old version), but this is inconsistent with the …

chore(deps): upgrade jsii, typescript & constructs in provider repos

---

.github/lib/collect-changes.js
.github/lib/create-pr.js
lib/repository.ts
main.ts

In preparation for possibly having to get rid of Mergify, this turns on GitHub's native automerge feature for all of the managed repos and also ensures that all the managed Constructs have the correct branch protection settings applied to them. Even if we keep Mergify and don't end up using automerge, having this turned on doesn't hurt us in any way.

feat: allow automerge workflow on managed repositories

---

lib/repository.ts

Supercedes #243 -- all this does is turn on the `archiveOnDestroy` flag for the future, it doesn't do anything with `hashicups` just yet while I build out a more formal workflow for deprecating providers.

feat: archive GitHub repos of deprecated providers

---

.github/workflows/automerge.yml
.github/workflows/diff-cdktf-stacks.yml

chore(ci): replace mergify with automerge workflow

---

lib/secrets.ts

Maven recently changed the credentials required for publishing:
As a reminder for future reference, the way publishing works is that we use publib through github actions within each prebuilt provider repository. The github action uses maven username and password through the repository secrets. The secrets there are written by `cdktf-repository-manager` (this repo) through Terraform. The secrets that are sent to the repository through Terraform are stored within an HCP Terraform variable set. 
While this PR only adds a comment to the secret, the true change happened within HCP Terraform. This PR was necessary to trigger the Terraform plan apply resulting in updating all Prebuilt provider repositories.

chore: Trigger update for maven credentials (and add comment)

---

lib/repository.ts

There have been a bunch of security alerts on our prebuilt provider repos recently due to dependencies like jsii and cross-spawn. These could be easily addressed by Dependabot since all they need to update is yarn.lock so they don't interfere with Projen. Enabling this will help to get security alerts addressed faster than trying to go through Projen.

chore: enable Dependabot security updates

---

lib/repository.ts

Refs: 508d0d9b83825af9ac429e98993ee9479f70fb9c, a860e4a461bb40df1ff5501185cda4687acc1f60
I think I found a bug with the [`repository_dependabot_security_updates` resource](https://registry.terraform.io/providers/integrations/github/latest/docs/resources/repository_dependabot_security_updates) in the GitHub provider. When I initially created it just using the simple repository name as the example suggests, I got the error:
```
Error: PUT https://api.github.com/repos/team-tf-cdk/cdktf-cdk8s/automated-security-fixes: 404 Not Found []
│ 
│   with github_repository_dependabot_security_updates.cdktf-construct-cdktf-cdk8s_dependabot-security_5AC81755 (cdktf-construct-cdktf-cdk8s/dependabot-security),
│   on cdk.tf.json line 1141, in resource.github_repository_dependabot_security_updates.cdktf-con …
```

revert: remove the addition of Dependabot security

---

.github/workflows/deploy-cdktf-stacks.yml
.github/workflows/upgrade-repositories.yml

There are breaking changes in the v2 upgrade of the Slack integration -- see hashicorp/terraform-releases#149
TODO:

chore(deps): update pinned versions of GitHub Actions

---

provider.json

Also moves the Snowflake provider to the new namespace.
Closes #380
Closes hashicorp/terraform-cdk#3877

feat: upgrade GitLab and Vault providers

---

.github/workflows/upgrade-repositories.yml
projenrc.template.js

We accidentally removed the actual building of the provider at the time of release. This PR fixes that, along with setting the correct version number within the prebuilt provider readme.

fix: Build provider and use the right version number for readme

---

provider.json

The latest version of the [vsphere provider](https://registry.terraform.io/providers/vmware/vsphere/latest) is now `vmware/vsphere` as opposed to `hashicorp/vsphere`. This PR now points the prebuilt provider to the new namespace

feat: Update VSphere provider to new namespace

---

.github/workflows/upgrade-repositories.yml

One of the consequences of bringing back `yarn fetch` in #389 is that because it nukes and recreates all of the contents of the `src/` directory, we lose the generated copyright headers, which is one of the reasons why these CI runs can generate PRs with thousands of changed files for some of the bigger providers like AWS, Google, etc.
I realized that another way to alleviate this problem is simply to regenerate the copyright headers as part of this workflow. This should result in diffs that are much, much smaller.

chore(ci): add copyright headers after running yarn fetch
