- main.ts
- provider.json
This will allow reading the data from other repos
> Move provider data into file

- provider.json
As requested in https://github.com/hashicorp/terraform-cdk/issues/888
> Add more providers

- projenrc.template.js
https://github.com/hashicorp/cdktf-provider-project/pull/198
> Configure versions in config file

- provider.json
Closes https://github.com/hashicorp/terraform-cdk/issues/1251
> feat: add helm provider

- provider.json
Resolves https://github.com/hashicorp/terraform-cdk/issues/1304
> add opentelekomcloud provider

- provider.json
Second PR for #32 since CI only works for internal folks
> Add newrelic provider

- .github/workflows/upgrade-repositories.yml
Resolves https://github.com/hashicorp/terraform-cdk/issues/1204
> feat: detect breaking version changes and adjust commit messages to provider repos accordingly

- provider.json
> Add Okta provider

- .github/workflows/upgrade-repositories.yml
prevented okta provider from being initialized
> fix: breaking change detection was broken for initial run for new providers

- lib/secret.ts
- main.ts
Currently PRs can not be created: https://github.com/hashicorp/cdktf-provider-docker/runs/4819543719?check_suite_focus=true
> fix: add PROJEN_GITHUB_TOKEN alias secret

- projenrc.template.js
https://github.com/hashicorp/terraform-cdk/releases/tag/v0.9.0
> chore!: upgrade to cdktf 0.9

- provider.json
Follow up for #52 since our CI does not work properly with forks.
Closes #52
> chore: add ionoscloud provider

- provider.json
Related to: https://github.com/hashicorp/cdktf-provider-google/issues/1041
> feat: update google provider to v4

- provider.json
Closes #58
We have to copy the commit to our own branch, otherwise CI won't work
> feat: add yandex provider

- provider.json
> feat: add gitlab provider

- .github/workflows/deploy.yml
- .github/workflows/diff.yml
- .github/workflows/upgrade-repositories.yml
- chore: prettify the github actions
- fix: ensure a changing provider name is a breaking change
> fix: make a breaking change if the provider name changes

- .github/workflows/deploy.yml
- lib/repository.ts
- package.json
- yarn.lock
- fix: pass tfc token
- chore: update cdktf
> fix: pass tfc token in deploy step

- .github/workflows/upgrade-repositories.yml
We must have accidentally deleted it
> fix: add label to add

- main.ts
We had built a bunch of workarounds during our transition to the new `cdktf` org. However, with that move now complete, all of that can be cleaned up.
> Fix: Clean-up after moving everything to `cdktf` org

- .github/lib/create-pr.js
- .github/workflows/upgrade-repositories.yml
Similar to: https://github.com/cdktf/cdktf-provider-project/pull/276
This PR uses the commit message to generate the PR title for upgrades
> fix: use commit message as PR title

- provider.json
Related to https://github.com/hashicorp/terraform-cdk/issues/2290
> feat: update newrelic to `~>3.7`

- .github/workflows/upgrade-repositories.yml
Fix workflow typo for creating next PRs
> fix: Add missing comma in script call

- .github/workflows/upgrade-repositories.yml
Should fix the AWS provider upgrade
> fix: make more memory available when upgrading repositories

- projenrc.template.js
draft, can only be merged after 0.14 has been released (i.e. NPM package etc is available)
> chore!: upgrade CDKTF to 0.14

- .github/workflows/gh-action-upgrade.yml
See saadmk11/github-actions-version-updater#49 for details
> chore: fix broken GHA version updater

- .github/ISSUE_TEMPLATE/request-provider.yml
Since we've gotten a few of these the last few days, I figured we should formalize the process. This was heavily inspired by the pypi/support repo.
> chore: add issue template for provider requests

- .github/workflows/add-license.yml
#174 was so old that there's been multiple newer versions of copywrite since...
> chore: update copywrite in Go license script

- provider.json
- sharded-stacks.json
Waypoint has an official provider now: https://registry.terraform.io/providers/hashicorp/waypoint/latest
> feat: add Waypoint provider

- .github/CODEOWNERS
- .github/lib/copy-codeowners-file.js
- .github/workflows/add-codeowners.yml
- .github/workflows/add-copyright-headers.yml
- .github/workflows/create-next-pr.yml
- .github/workflows/deploy-cdktf-stacks.yml
- .github/workflows/deploy.yml
- .github/workflows/diff-cdktf-stacks.yml
- .github/workflows/diff.yml
- .github/workflows/gh-action-upgrade.yml
- .github/workflows/lock.yml
- .github/workflows/stale.yml
- .github/workflows/upgrade-repositories.yml
- assets/codeowners
While working on #206 today, I discovered lots of small housekeeping-type things that could be improved with our actions.
The most consequential of these is:
https://github.com/cdktf/cdktf-repository-manager/blob/59b0ad5e300f71491f8411d9e530202cd8af5b66/.github/workflows/upgrade-repositories.yml#L99-L100
This will allow us to retry calls that fail due to rate limits, which might help alleviate the issue where sometimes, the PRs don't get merged because the "automerge" label didn't get added. Worth a try, anyway!
> chore(deps): github actions housekeeping

- .github/workflows/upgrade-node.yml
- package.json
- scripts/check-node-versions.js
- yarn.lock
This adapts the script I used to automate upgrading Node.js in cdktf-aws-cdk. This is my first time using this script completely outside of Projen so it may require a little bit of testing and tweaking until it's working completely right.
> feat: automate upgrading Node.js

- .github/workflows/upgrade-terraform.yml
I was wondering why https://github.com/cdktf/cdktf-repository-manager/actions/runs/6450639030/job/17510215802 didn't result in a PR to upgrade to TF 1.6 and realized it's because of the quotes.
> chore: fix upgrade-terraform workflow

- provider.json
v3 was released last week: https://github.com/UpCloudLtd/terraform-provider-upcloud/releases
> chore: update UpCloud to v3

- .github/workflows/deprecate-provider.yml
- projenrc.template.js
cdktf/cdktf-provider-project#370 must be merged and published before this has any effect.
> feat: create workflow to deprecate a provider

- .github/workflows/deprecate-provider.yml
- projenrc.template.js
- providersWithCustomRunners.json
Couple of typo and small cosmetic fixes.
Let's wait to merge this until Monday morning because I don't want to introduce any chances of providers failing to publish over the weekend.
> chore: wrap up work started in #246

- provider.json
> feat: upgrade Github provider version from 5.x to 6.x

- provider.json
> chore: update upcloud provider to 5.0

- provider.json
> chore: upgrade vault provider version to 4.0

- provider.json
Update gitlab prebuilt provider to support latest terraform provider version.
> feat: Upgrade gitlab provider from v16 to v17

- lib/repository.ts
~I think I tried this once before and it didn't do anything in practice, but I can't remember for sure.~ It seems to do... something? Need to deploy the change to be sure...
> chore: enable vulnerability alerts

- provider.json
> Update Azure to 4.0+

- provider.json
> Update azuread provider major version to v3

- provider.json
> Update snowflake to 1.0+

- lib/repository.ts
An hour after giving up on #342 and reverting it in #343, I figured out what I had missed. That's how it always goes, right?
> chore: enable Dependabot security updates
